# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ask < Formula
  desc "Your AI Terminal Expert | 你的 AI 终端指令专家"
  homepage "https://github.com/shanhai1024/aiAsk"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shanhai1024/aiAsk/releases/download/v1.0.0/aiAsk_1.0.0_darwin_amd64.tar.gz"
      sha256 "02903c23e4aefecc7d1c959dd9fd0378489f8e9c003edb175476335f0d2196d0"

      def install
        bin.install "ask"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shanhai1024/aiAsk/releases/download/v1.0.0/aiAsk_1.0.0_darwin_arm64.tar.gz"
      sha256 "e32e3ab4c6d448c1172c1d55a8281634d72e632ff88f89203239023709e7b7bf"

      def install
        bin.install "ask"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shanhai1024/aiAsk/releases/download/v1.0.0/aiAsk_1.0.0_linux_amd64.tar.gz"
      sha256 "16a8cb6fd6c7b9efbcf963402a592c38fb6bb21f77fc53db70085016071f7a96"
      def install
        bin.install "ask"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shanhai1024/aiAsk/releases/download/v1.0.0/aiAsk_1.0.0_linux_arm64.tar.gz"
      sha256 "88b0e22b15a0129fd423d665ccd3460e1d64ac8e9a5c0f466f4e43fe4867c29c"
      def install
        bin.install "ask"
      end
    end
  end
end
