# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ask < Formula
  desc "Your AI Terminal Expert | 你的 AI 终端指令专家"
  homepage "https://github.com/shanhai1024/aiAsk"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shanhai1024/aiAsk/releases/download/v1.0.1/aiAsk_1.0.1_darwin_amd64.tar.gz"
      sha256 "16a639bf9486862fafc842ae94cdb67250f02b7c8c0e5405147b5c620b6ff86b"

      def install
        bin.install "ask"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shanhai1024/aiAsk/releases/download/v1.0.1/aiAsk_1.0.1_darwin_arm64.tar.gz"
      sha256 "6545db4e6c86f9e021630359471955a339566c8afd8879ff0c4d9dd059582b73"

      def install
        bin.install "ask"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shanhai1024/aiAsk/releases/download/v1.0.1/aiAsk_1.0.1_linux_amd64.tar.gz"
      sha256 "13484f91e3860d22a20ddfcc06e7b76b2cd8b6a0cad83cb778ed8dc1624c6873"
      def install
        bin.install "ask"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shanhai1024/aiAsk/releases/download/v1.0.1/aiAsk_1.0.1_linux_arm64.tar.gz"
      sha256 "a1031191cbb37fb2d44e41b52ce581c05c036c25cf3ad5b01ef280e022ab7a4e"
      def install
        bin.install "ask"
      end
    end
  end
end
